  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
      paths:
        - "src/**"
    workflow_dispatch: # on button click

  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
            with:
              token: ${{ secrets.PAT }}
          - uses: actions/setup-node@v3
            with:
              node-version: '20'
              cache: 'npm'
          - name: Install packages
            run: npm i
          - name: Set Creds
            run: git config user.name "DreamNya" && git config user.email "34838824+DreamNya@users.noreply.github.com"
          - name: Deploy
            run: npm run deploy
